version: "3.9"
services:
  web:
    build: .
    environment:
      NEO4J_URL: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4j1
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: 'neo4j/neo4j1'
    ports:
        - "7687:7687"
        - "7474:7474"